#!/usr/bin/env python
#coding=utf-8
import paramiko
import time

hostname='10.89.90.7'
username='user'
password='passwd'

try :
    paramiko.util.log_to_file('paramiko.log')
    s=paramiko.SSHClient()
    s.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    s.connect(hostname=hostname,username=username,password=password)

#    channel = s.invoke_shell()
#    time.sleep(2)

#    channel.send('show policy id 1\n')
#    time.sleep(1)
#    output = channel.recv(2048)
#    print output

    stdin,stdout,stderr=s.exec_command('show policy id 1')
    stdin,stdout,stderr=s.exec_command('\n')
    print stderr.read(),stdout.read()

    s.close()
except Exception as e:
    print e
